clusterName: ["k8s-prod", "k8s-stage"]
project: "project1"
registryCredentialsId: "nexus_admin"
registryImageUrl: "artifacts-docker.example.com"
defaultValues: "./.helm/values.yaml"
microserviceValues: "./.helm/microservice_values.yaml"
secretValues: "./.helm/secret_values.yaml"
serviceAccount: "deploy-agent"
gitCredentialsId: "jenkins-cicd"
secret:
    provider: vault
    vaultUrl: "https://vault.example.com"
    vaultAppRoleCredential: "jenkins-role-backend"
yaml: |-
    spec:
    hostAliases:
    - ip: '10.0.0.35'
    hostnames:
        - 'jenkins.example.com'
