{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.microservice.name }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret }}
  {{- $environmentValue := $value | toString }}
  {{- if $environmentValue }}
  {{ $key }}: {{ $environmentValue | b64enc }}
  {{- end }}
  {{- end }}
{{- end }}
